frontend/controllers/AuthController.php
<?php

declare(strict_types=1);

namespace frontend\controllers;

use frontend\forms\Login;

class AuthController extends \yii2kernel\web\Controller
{
    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\InvalidParamException
     */
    public function actionLogin()
    {
        $formModel = new Login();

        if ($formModel->load(\Yii::$app->getRequest()->post())) {
            $formModel->save();

            if (\Yii::$app->getRequest()->getIsAjax()) {
                return $this->json([], $formModel->getErrors());
            }

            if ($formModel->hasErrors() === false) {
                return $this->goBack();
            }
        }

        return $this->render('login', [
            'formModel' => $formModel,
        ]);
    }

    public function actionLogout()
    {
        \Yii::$app->getUser()->logout();

        if (\Yii::$app->getRequest()->getIsAjax()) {
            return $this->json();
        }

        return $this->goHome();
    }
}

frontend/controllers/PageController.php
<?php

declare(strict_types=1);

namespace frontend\controllers;

use yii\web\ViewAction;
use yii2kernel\web\Controller;

class PageController extends Controller
{
    public function actions()
    {
        return [
            'view' => [
                'class'      => ViewAction::class,
                'viewParam'  => 'view',
                'viewPrefix' => null,
            ],
        ];
    }
}

frontend/controllers/SiteController.php
<?php

declare(strict_types=1);

namespace frontend\controllers;

use yii\web\ErrorAction;
use yii2kernel\web\Controller;

class SiteController extends Controller
{
    public function actions(): array
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
}

frontend/views/layouts/main.php
<?php

/**
 * @var \yii2kernel\web\View $this
 * @var string               $content
 */

declare(strict_types=1);

use yii\helpers\Html;

\frontend\assets\LayoutAsset::register($this);

?>

<?php $this->beginPage(); ?>

<!DOCTYPE html>
<html lang="<?= \Yii::$app->language; ?>">
<head>
    <meta charset="<?= \Yii::$app->charset; ?>">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title ? : \Yii::$app->name); ?></title>
    <?php $this->head(); ?>
</head>
<body>

<?php $this->beginBody(); ?>

<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#header-navbar"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/"><?= Yii::$app->name; ?></a>
            </div>

            <div class="collapse navbar-collapse" id="header-navbar">
                <?= \yii\bootstrap\Nav::widget([
                    'items'   => [
                        [
                            'url'   => ['/site/index'],
                            'label' => Yii::t('app', 'Main page'),
                        ],
                        [
                            'url'     => ['/auth/login'],
                            'label'   => Yii::t('app', 'Sign in'),
                            'visible' => Yii::$app->getUser()->getIsGuest(),
                        ],
                        [
                            'url'     => ['/auth/logout'],
                            'label'   => Yii::t('app', 'Sign out'),
                            'visible' => Yii::$app->getUser()->getIsGuest() === false,
                        ],
                    ],
                    'options' => [
                        'class' => 'nav navbar-nav',
                    ],
                ]); ?>
            </div>
        </div>
    </nav>
</header>

<div class="page-wrapper">
    <?= $content; ?>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y'); ?></p>

        <p class="pull-right"><?= \Yii::powered(); ?></p>
    </div>
</footer>

<?php $this->endBody(); ?>

</body>
</html>

<?php $this->endPage(); ?>

frontend/views/site/error.php
<?php

/**
 * @var \yii2kernel\web\View $this
 * @var string               $name
 * @var string               $message
 * @var \yii\base\Exception  $exception
 */

declare(strict_types=1);

?>

<section class="section-site-error">
    <div class="container">
        <div class="title"><?= $name; ?></div>
        <div class="description"><?= $message; ?></div>
    </div>
</section>

frontend/views/site/index.php
<?php

/**
 * @var \yii2kernel\web\View $this
 */

declare(strict_types=1);
?>
<section class="section-site-index">
    <div class="container">
        <div class="jumbotron">
            <h1><?= Yii::$app->name; ?></h1>
        </div>
    </div>
</section>